server.port=4000

# Backend API URL (overridable via environment variable)
backend.api.url=${API_URL:http://localhost:8000}

# Harness Feature Flag SDK key
harness.ff.sdk.key=${FF_SDK_KEY:7aec20a0-d867-42fa-8979-609f80937411}
